# Generated by Django 4.2.3 on 2023-07-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shortener", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="status",
            field=models.CharField(
                choices=[("A", "Active"), ("I", "Inactive")], default="A", max_length=1
            ),
        ),
    ]
